update: dependecies
Compiling with Rust 1.80 failed:

```
   Compiling form_urlencoded v1.2.0
   Compiling anstyle-parse v0.2.1
   Compiling time v0.3.25
   Compiling rustls-pemfile v1.0.3
   Compiling object v0.31.1
   Compiling aho-corasick v1.0.2
error[E0282]: type annotations needed for `Box<_>`
  --> /home/b10c/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.25/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

This is a known issue, as Rust 1.80 had a minor breaking change that
broke the `time` crate.

Updating the dependecies resolves this.

    Updating addr2line v0.20.0 -> v0.24.1
    Removing adler v1.0.2
      Adding adler2 v2.0.0
    Updating aho-corasick v1.0.2 -> v1.1.3
    Updating anstream v0.3.2 -> v0.6.15
    Updating anstyle v1.0.1 -> v1.0.8
    Updating anstyle-parse v0.2.1 -> v0.2.5
    Updating anstyle-query v1.0.0 -> v1.1.1
    Updating anstyle-wincon v1.0.1 -> v3.0.4
    Updating arc-swap v1.6.0 -> v1.7.1
    Updating async-recursion v1.0.4 -> v1.1.1
    Updating async-trait v0.1.72 -> v0.1.83
    Updating autocfg v1.1.0 -> v1.3.0
    Updating backtrace v0.3.68 -> v0.3.74
    Updating base64 v0.21.2 -> v0.21.7 (latest: v0.22.1)
    Removing bitflags v1.3.2
    Removing bitflags v2.3.3
      Adding bitflags v2.6.0
    Updating bumpalo v3.13.0 -> v3.16.0
    Updating bytes v1.4.0 -> v1.7.2
    Updating cc v1.0.81 -> v1.1.21
    Updating chrono v0.4.26 -> v0.4.38
    Updating clap v4.3.19 -> v4.5.18
    Updating clap_builder v4.3.19 -> v4.5.18
    Updating clap_derive v4.3.12 -> v4.5.18
    Updating clap_lex v0.5.0 -> v0.7.2
    Updating colorchoice v1.0.0 -> v1.0.2
    Updating core-foundation v0.9.3 -> v0.9.4 (latest: v0.10.0)
    Updating core-foundation-sys v0.8.4 -> v0.8.7
    Updating deranged v0.3.7 -> v0.3.11
    Updating either v1.9.0 -> v1.13.0
    Updating env_logger v0.10.0 -> v0.10.2 (latest: v0.11.5)
    Removing errno v0.3.2
    Removing errno-dragonfly v0.1.2
    Updating form_urlencoded v1.2.0 -> v1.2.1
    Updating futures v0.3.28 -> v0.3.30
    Updating futures-channel v0.3.28 -> v0.3.30
    Updating futures-core v0.3.28 -> v0.3.30
    Updating futures-executor v0.3.28 -> v0.3.30
    Updating futures-io v0.3.28 -> v0.3.30
    Updating futures-macro v0.3.28 -> v0.3.30
    Updating futures-sink v0.3.28 -> v0.3.30
    Updating futures-task v0.3.28 -> v0.3.30
    Updating futures-util v0.3.28 -> v0.3.30
      Adding getrandom v0.2.15
    Updating gimli v0.27.3 -> v0.31.0
      Adding heck v0.5.0
    Removing hermit-abi v0.3.2
      Adding hermit-abi v0.3.9 (latest: v0.4.0)
      Adding hermit-abi v0.4.0
    Updating http v0.2.9 -> v0.2.12 (latest: v1.1.0)
    Updating http-body v0.4.5 -> v0.4.6 (latest: v1.0.1)
    Updating httparse v1.8.0 -> v1.9.4
    Updating httpdate v1.0.2 -> v1.0.3
    Updating hyper v0.14.27 -> v0.14.30 (latest: v1.4.1)
    Updating hyper-rustls v0.24.1 -> v0.24.2 (latest: v0.27.3)
    Updating iana-time-zone v0.1.57 -> v0.1.61
    Updating idna v0.4.0 -> v0.5.0 (latest: v1.0.2)
    Updating is-terminal v0.4.9 -> v0.4.13
      Adding is_terminal_polyfill v1.70.1
    Updating itoa v1.0.9 -> v1.0.11
    Updating js-sys v0.3.64 -> v0.3.70
    Updating libc v0.2.147 -> v0.2.159
    Removing linux-raw-sys v0.4.5
    Updating log v0.4.19 -> v0.4.22
    Updating memchr v2.5.0 -> v2.7.4
    Updating miniz_oxide v0.7.1 -> v0.8.0
    Updating mio v0.8.8 -> v1.0.2
    Updating num-bigint v0.4.3 -> v0.4.6
      Adding num-conv v0.1.0
    Updating num-integer v0.1.45 -> v0.1.46
    Updating num-traits v0.2.16 -> v0.2.19
    Removing num_cpus v1.16.0
    Updating object v0.31.1 -> v0.36.4
    Updating once_cell v1.18.0 -> v1.19.0
    Updating percent-encoding v2.3.0 -> v2.3.1
    Updating pin-project v1.1.2 -> v1.1.5
    Updating pin-project-internal v1.1.2 -> v1.1.5
    Updating pin-project-lite v0.2.10 -> v0.2.14
      Adding powerfmt v0.2.0
    Updating proc-macro2 v1.0.66 -> v1.0.86
    Updating quote v1.0.32 -> v1.0.37
    Updating regex v1.9.1 -> v1.10.6
    Updating regex-automata v0.3.4 -> v0.4.7
    Updating regex-syntax v0.7.4 -> v0.8.4
      Adding ring v0.17.8
    Updating rustc-demangle v0.1.23 -> v0.1.24
    Removing rustix v0.38.6
    Updating rustls v0.21.6 -> v0.21.12 (latest: v0.23.13)
    Updating rustls-pemfile v1.0.3 -> v1.0.4 (latest: v2.1.3)
    Updating rustls-webpki v0.101.2 -> v0.101.7 (latest: v0.102.8)
    Updating ryu v1.0.15 -> v1.0.18
    Updating schannel v0.1.22 -> v0.1.24
    Updating sct v0.7.0 -> v0.7.1
    Updating security-framework v2.9.2 -> v2.11.1 (latest: v3.0.0)
    Updating security-framework-sys v2.9.1 -> v2.12.0
    Updating serde v1.0.181 -> v1.0.210
    Updating serde_derive v1.0.181 -> v1.0.210
    Updating serde_json v1.0.104 -> v1.0.128
    Updating serde_path_to_error v0.1.14 -> v0.1.16
      Adding shlex v1.3.0
    Updating slab v0.4.8 -> v0.4.9
    Updating socket2 v0.4.9 -> v0.5.7
      Adding spin v0.9.8
    Updating strsim v0.10.0 -> v0.11.1
    Updating syn v2.0.28 -> v2.0.77
    Updating termcolor v1.2.0 -> v1.4.1
    Updating thiserror v1.0.44 -> v1.0.64
    Updating thiserror-impl v1.0.44 -> v1.0.64
    Removing time v0.1.45
    Removing time v0.3.25
      Adding time v0.3.36
    Updating time-core v0.1.1 -> v0.1.2
    Updating time-macros v0.2.11 -> v0.2.18
    Updating tinyvec v1.6.0 -> v1.8.0
    Updating tokio v1.29.1 -> v1.40.0
    Updating tokio-macros v2.1.0 -> v2.4.0
    Updating tokio-util v0.7.8 -> v0.7.12
    Updating tower-http v0.4.3 -> v0.4.4 (latest: v0.6.1)
    Updating tower-layer v0.3.2 -> v0.3.3
    Updating tower-service v0.3.2 -> v0.3.3
    Updating tracing v0.1.37 -> v0.1.40
    Updating tracing-attributes v0.1.26 -> v0.1.27
    Updating tracing-core v0.1.31 -> v0.1.32
    Updating try-lock v0.2.4 -> v0.2.5
    Updating unicode-bidi v0.3.13 -> v0.3.15
    Updating unicode-ident v1.0.11 -> v1.0.13
    Updating unicode-normalization v0.1.22 -> v0.1.24
      Adding untrusted v0.9.0
    Updating url v2.4.0 -> v2.5.2
    Updating utf8parse v0.2.1 -> v0.2.2
    Removing wasi v0.10.0+wasi-snapshot-preview1
    Updating wasm-bindgen v0.2.87 -> v0.2.93
    Updating wasm-bindgen-backend v0.2.87 -> v0.2.93
    Updating wasm-bindgen-macro v0.2.87 -> v0.2.93
    Updating wasm-bindgen-macro-support v0.2.87 -> v0.2.93
    Updating wasm-bindgen-shared v0.2.87 -> v0.2.93
    Updating web-sys v0.3.64 -> v0.3.70
    Updating winapi-util v0.1.5 -> v0.1.9
    Removing windows v0.48.0
      Adding windows-core v0.52.0 (latest: v0.58.0)
    Removing windows-sys v0.48.0
      Adding windows-sys v0.52.0 (latest: v0.59.0)
      Adding windows-sys v0.59.0
    Updating windows-targets v0.48.1 -> v0.52.6
    Updating windows_aarch64_gnullvm v0.48.0 -> v0.52.6
    Updating windows_aarch64_msvc v0.48.0 -> v0.52.6
    Updating windows_i686_gnu v0.48.0 -> v0.52.6
      Adding windows_i686_gnullvm v0.52.6
    Updating windows_i686_msvc v0.48.0 -> v0.52.6
    Updating windows_x86_64_gnu v0.48.0 -> v0.52.6
    Updating windows_x86_64_gnullvm v0.48.0 -> v0.52.6
    Updating windows_x86_64_msvc v0.48.0 -> v0.52.6
    Updating zeroize v1.6.0 -> v1.8.1